color_correspondence_dict = {"white":"ホワイト（白）系",
                             "black":"ブラック（黒）系",
                             "gray":"グレー（灰色）系",
                             "brown":"ブラウン（茶色）系",
                             "beige":"ベージュ系",
                             "green":"グリーン（緑）系",
                             "blue":"ブルー（青）系",
                             "navy":"ネイビー（紺）系",
                             "purple": "パープル（紫）系",
                             "yellow": "イエロー（黄色）系",
                             "pink": "ピンク系",
                             "red": "レッド（赤）系",
                             "orange": "オレンジ系",
                             "silver": "シルバー（銀色）系",
                             "gold": "ゴールド（金色）系",
                             "clear": "クリア（透明）系",
                             "multi": "マルチカラー"}